added base64
google/mesop pull request #415
Opened 2024-06-11 04:58 UTC by zacharias1219

2024-06-11 15:29 UTC, richard-to requested changes
This is a good start. Let's add some test coverage now. 

You'll need tests for:

- mesop/dataclass_utils/dataclass_utils_test.py
- mesop/dataclass_utils/diff_state_test.py 
- mesop/web/src/utils/diff_state_spec.ts

To run the specific tests:

```
bazel test //mesop/dataclass_utils:dataclass_utils_test
bazel test //mesop/dataclass_utils:diff_state_test
bazel test //mesop/web/src/utils:unit_test
```

2024-06-11 15:29 UTC, richard-to commented on mesop/dataclass_utils/dataclass_utils.py
> +_BYTES_OBJECT_KEY = "__python.bytes.__" # Add new key for bytes
[nit] Can you remove the extra period at the end of bytes: `__python.bytes__`

2024-06-11 17:42 UTC, zacharias1219 commented
Hey I've added tests and removed the period

2024-06-11 18:02 UTC, richard-to commented
For `diff_test_spec.ts`, can you add an example for bytes (there's a lot of formatting changes, so it's possible I missed the test case there)?

Also for dataclass_utils_test, can you add a couple more examples for test_serialize_bytes(), such as empty string and maybe something with unicode characters. For those tests you can use pytest parametrized tests: https://docs.pytest.org/en/7.1.x/how-to/parametrize.html#pytest-mark-parametrize-parametrizing-test-functions

2024-06-11 18:03 UTC, richard-to commented
Also in your PR description, can you reference the issue number?

2024-06-12 02:03 UTC, zacharias1219 commented
Hey I've made changes as requested.

And extremely sorry about the formatting change, whenever i saved the file it suddenly showed all blue changed lines and I didn't know why, thought there was an error with my editor.

2024-06-12 03:15 UTC, richard-to requested changes
Thanks for making those changes. This looks good. I added a few minor comments about removing unnecessary comments. But after I can approve and merge this PR in for you. Thanks!

2024-06-12 03:15 UTC, richard-to commented on mesop/dataclass_utils/dataclass_utils.py
> +import base64 # Import base64 for encoding
[nit] Usually don't need to add a comment for why you're importing something. So can remove it.

2024-06-12 03:15 UTC, richard-to commented on mesop/dataclass_utils/dataclass_utils.py
> +_BYTES_OBJECT_KEY = "__python.bytes__" # Add new key for bytes
[nit] This comment is self-explanatory with the code, so no needed.

2024-06-12 03:15 UTC, richard-to commented on mesop/dataclass_utils/dataclass_utils.py
> +      return {_BYTES_OBJECT_KEY: base64.b64encode(obj).decode('utf-8')} # Encode bytes
[nit] Same here. We can assume the reader of the code can read what the code is doing. Usually you want to add comments that are not self-explanatory. For example, the reason why something is being done which may not be intuitive to the reader of the code.

2024-06-12 03:15 UTC, richard-to commented on mesop/dataclass_utils/dataclass_utils.py
> +    return base64.b64decode(dct[_BYTES_OBJECT_KEY]) # Decode bytes
[nit] Same here. We can assume the reader of the code can read what the code is doing. Usually you want to add comments that are not self-explanatory. For example, the reason why something is being done which may not be intuitive to the reader of the code.

2024-06-12 05:10 UTC, richard-to commented
Looks like the linting presubmit failed. Can you adjust based on the errors there. You can also install the precommit checks for checking. See https://google.github.io/mesop/internal/development/

2024-06-12 06:14 UTC, zacharias1219 commented
Yes i'll look in it.

2024-06-12 06:35 UTC, zacharias1219 commented
Hey so from what I understood, I was told to change the ci.yml file, can we do that?

2024-06-12 06:50 UTC, zacharias1219 commented
I'm not sure if the changes that I made are correct, i just ran pre-commit and it made some changes of it's own.

2024-06-12 14:42 UTC, richard-to commented
Yes, part of the  precommit steps will run formatting checks to make sure the code is formatted consistently in our codebase.

Can you run `pre-commit run --all-files`. This should update the formatting for: mesop/web/src/utils/diff_state_spec.ts

Example of the changes it needs to make for be consistent:

<img width="707" alt="Screenshot 2024-06-12 at 7 40 03 AM" src="https://github.com/google/mesop/assets/539889/2cc1272f-81ae-4bb4-a7e5-62044b5d9d21">

2024-06-12 16:03 UTC, zacharias1219 commented
Okay.
When I did that, it changed all the files, should I commit all the files or just mesop/web/src/utils/diff_state_spec.ts

2024-06-12 16:14 UTC, richard-to commented
Oh yeah, you should just include `mesop/web/src/utils/diff_state_spec.ts`. I'm running the pre-submit again. 🤞🏾

2024-06-12 16:17 UTC, zacharias1219 commented
Ahh man thought it would be done.

2024-06-12 16:18 UTC, zacharias1219 commented
Hold on it changed the files again when I ran pre-commit run --all-files

2024-06-12 16:28 UTC, zacharias1219 commented
There are some changes in .pre-commit-config.yml as well, should i keep those changes??

2024-06-12 16:34 UTC, richard-to commented
Leave the .pre-commit-config.yaml  as is for now. Just upload the change to: mesop/dataclass_utils/dataclass_utils.py

I think that should be it.

2024-06-12 16:41 UTC, zacharias1219 commented
Hey I done the changes, hopefully it's the last one.
I'll keep this step in check before doing pr's next time, sorry for all the headache.

2024-06-12 16:43 UTC, richard-to commented
> Hey I done the changes, hopefully it's the last one.
I'll keep this step in check before doing pr's next time, sorry for all the headache.

It's not a problem at all. I think this just tells us that we need to improve our documentation for setting up the dev environment better. That's usually the most annoying part which is partially why we've been working on setting up Docker Images and Github Codespaces.

2024-06-12 16:44 UTC, zacharias1219 commented
I genuinely don't know why it's going wrong

2024-06-12 16:56 UTC, zacharias1219 commented
![image](https://github.com/google/mesop/assets/132373453/b8e60602-8a79-454e-8559-ddddc0a5a0f9)
Okay I made changes, however it's showing failed for these two, don't know what to do here, could you help.

2024-06-12 17:01 UTC, zacharias1219 commented
Yes this is what i've change just now, however there are other two errors that I'm getting.

2024-06-12 17:08 UTC, zacharias1219 commented
Okay this run seems promising.

2024-06-12 17:18 UTC, richard-to commented
Looks like the next thing to fix is the unit tests.

For this test, "test_diff_bytes_fails" you can delete it now that we have support for bytes.

To run the tests locally:

```
bazel test //mesop/dataclass_utils:dataclass_utils_test
```

2024-06-12 18:23 UTC, zacharias1219 commented
Okay 1 test reduced at least. I'll look into the other one.

2024-06-12 18:33 UTC, zacharias1219 commented
Hey, Hopefully this works, I'll be going to sleep right now, it's really late here, will work on it tomorrow if it fails.

2024-06-12 19:35 UTC, zacharias1219 commented
What version of bazel do you recommend for this?
Because the checks that I'm doing on my local machine are passing but not after you start the checking process.

2024-06-12 19:51 UTC, richard-to commented
> What version of bazel do you recommend for this? Because the checks that I'm doing on my local machine are passing but not after you start the checking process.

Looking at the error, do you think there is something non-deterministic with the base64 encoding or something? Seems like you get a different encoding your local machine than on the CI machine.

I think for now you can just remove unicode test.

2024-06-13 01:46 UTC, zacharias1219 commented
Is this it, I'm not sure at this point.

2024-06-13 07:21 UTC, zacharias1219 commented
The pre checks were all fine for this and checked the bazel test, no errors hopefully this is the last one.

2024-06-13 13:59 UTC, merged

2024-06-13 13:59 UTC, richard-to commented
Ok, looks like it passed. Thanks for you patience on this @zacharias1219.

2024-06-13 14:33 UTC, zacharias1219 commented
Ohh thank god, finally.

2024-06-13 14:35 UTC, zacharias1219 commented
Is there anything I should do more, and yeah I should be thanking you for being patient.

2024-06-13 14:39 UTC, richard-to commented
I think that's it for this issue.

On Thu, Jun 13, 2024 at 7:35 AM Richard Abishai ***@***.***>
wrote:

> Is there anything I should do more, and yeah I should be thanking you for
> being patient.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/google/mesop/pull/415#issuecomment-2165860204>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAEDZ4I3KEMLPF5DKSWZC4LZHGU27AVCNFSM6AAAAABJDRGVZOVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCNRVHA3DAMRQGQ>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2024-06-13 14:51 UTC, zacharias1219 commented
Thank you so much for being a good mentor during this pr. I'll look forward to contributing more to this project.