add more border styles to BorderSide style element
google/mesop pull request #504
Opened 2024-06-23 04:05 UTC by seekerquest

Add dashed", "dotted", "double", "groove", "ridge", "inset", "outset" to BorderSide class

2024-06-23 16:12 UTC, richard-to requested changes
Can you also update "box" demo example to use some of the added styles? That's just to make sure we have an example of it working. See: https://github.com/google/mesop/blob/main/demo/box.py

--------

Also looks like someone else also posted a pull request for the border side change after you: https://github.com/google/mesop/pull/509. Looks like what happened is that they didn't see your message. And I had referred that person to this issue from another issue.

Since you were first, I will give your pull request precedence.

2024-06-23 16:12 UTC, richard-to commented on mesop/component_helpers/style.py
> +      style: The style of the border, which can be 'none' for no border, 'solid' for a solid line, 'dashed' for dashed line,
Maybe you can link to this as well: https://developer.mozilla.org/en-US/docs/Web/CSS/border-style

2024-06-23 16:12 UTC, richard-to commented on mesop/component_helpers/style.py
> +  style: Literal["none", "solid", "dashed", "dotted", "double", "groove", "ridge", "inset", "outset"] | None = None
Seems like there is also a "hidden" style, which seems slightly different than none. So we may want to add it for completeness.

2024-06-23 18:24 UTC, richard-to approved these changes
LGTM - Thanks

2024-06-23 18:37 UTC, richard-to commented
Looks like the pre-submit checks failed. Just some linting stuff. The best option is to set up the pre-commits described here: https://google.github.io/mesop/internal/development/

The precommits should manually run the ruff formatter to fix the formatting.

For a manual run, I think the command is something like:

```
pre-commit run --files FILES
```

2024-06-24 00:16 UTC, seekerquest commented
Thanks for sharing the steps to fix the pre-checks. I think this has now passed the pre-checks.

2024-06-24 18:43 UTC, richard-to commented
Hmm looks like there is another type checking issue on the demo page. It's an interesting one. I'm not quite sure how best to resolve that type checking issue.

For simplicity, you may just want to remove the loop. Then for the styles, just hardcode to different styles.

2024-07-02 05:05 UTC, richard-to commented
Closing this one. We ended up merging a similar pull request in https://github.com/google/mesop/pull/509

2024-07-02 05:05 UTC, closed without merging