ADD demo/authentication
google/mesop pull request #625
Opened 2024-07-16 10:11 UTC by itsBaivab

FIX : CI test fails

2024-07-16 10:13 UTC, itsBaivab commented
PR for #608

2024-07-16 14:34 UTC, richard-to requested changes
Overall, it looks fine. Thanks for the contribution. I think it's illustrated some missing functionality in Mesop as a framework around how it handles sensitive information like passwords and also being able to control access to pages. So these may be some things we need to figure for Mesop, either patterns or framework improvements, before we can merge this example in.

2024-07-16 14:34 UTC, richard-to commented on demo/authenticator.py
> +    state.username = ""
Good idea to clear these fields, especially password. 

Sorry for the delay on this review. I've just been thinking about if it's safe in Mesop to store the password in state. Ideally, we'd only send the password for the log in check (but never send it back). But I don't think that's currently possible in Mesop. The blur event helps in that at least we're not repeatedly sending parts of the password back and forth via the on input event.

I'm still not sure at the moment.

2024-07-16 14:34 UTC, richard-to commented on demo/authenticator.py
> +    s = me.state(State)
[suggestion] Maybe add an example of redirecting the user to the log in page if not logged in. We may also want to simulate a log out flow as well.

I think this is another area where Mesop may be lacking in terms of the API. For example, if a user is not allowed to view the page, we may want to return a 401 http code and error page. But again, not something I think Mesop is able to do at the moment.

2024-07-16 14:34 UTC, richard-to commented on tools/defaults.bzl
> +            cmd = """\r
[nit] can you revert this?

2024-08-24 20:54 UTC, richard-to commented
Going to close this pull request since I don't think we have a clear way forward for authentication interfaces yet.

2024-08-24 20:54 UTC, closed without merging